using System.Collections.Generic;
using System.IO;
using System.Linq;

using JackTheEnumRipper.Core;
using JackTheEnumRipper.Interfaces;
using JackTheEnumRipper.Models;

namespace Serializer
{
    public class IniSerializer : ISerializer
    {
        public Format Format => Format.Ini;

        public void Serialize(IEnumerable<AbstractEnum> enums, string path)
        {
            string comment = "This code was generated by a tool.";

            var sections = enums.Select(@enum => new Section
            {
                Comment = $"scope={(@enum.IsPublic ? "public" : "internal")},type={@enum.Type}",
                Name = $"{@enum.Namespace}.{@enum.Name}",
                Settings = @enum.Fields.Select(field => new Setting
                {
                    Name = field.Name,
                    Value = field.Value,
                }),
            }); ;

            var ini = new Ini(sections, comment, commentSymbol: '#');
            File.WriteAllText(path, ini.ToString());
        }
    }
}